/* =============================================================================================
 * Exploring the Structure of the database: allows us to get an idea of what we're working with! 
   =============================================================================================*/

-- Explore all objects in the database 
select * from information_schema."tables"; 

-- Explore all columns in the database 
select * from information_schema.columns
where table_name = 'dim_customers';

/* =============================================================================================
 * Dimension Exploration: identifying unique values in each dimension (categories) 
 * Recognizing how data might be grouped or segmented is useful for later analysis
   =============================================================================================*/

-- Explore all countries our customers come from. Helps us understand our geographical spread! 
select distinct country from gold.dim_customers;

-- Explore all categories 'the major divisions'
select distinct category, subcategory, product_name from gold.dim_products
order by 1,2,3;

/* =============================================================================================
 * Date Exploration: identify the earliest and latest date (boundaries) 
 * Understand the scope of data and the timespan
   =============================================================================================*/
select min(start_date), max(start_date) from gold.dim_products;
select min(order_date) as first_order_date, max(order_date) as last_order_date, extract(year from age (max(order_date),min(order_date))) as order_range_years from gold.fact_sales;
select min(birthdate), max(birthdate), extract(year from age(max(birthdate), min(birthdate))) as old_young_gap from gold.dim_customers; 

/* =============================================================================================
 * Measures Exploration: Calculate and find the key metrics of the business (Big numbers) 
 * The highest level of aggregation | Lowest level of details 
   =============================================================================================*/

-- Generate a report that shows all key metrics of the business 
select 'Total Sales' as measure_name, sum(sales_amount) as measure_value from gold.fact_sales
union all 
select 'Total Quantity' as measure_name, sum(quantity) as measure_value from gold.fact_sales
union all 
select 'Average Price' as measure_name, round(avg(price),2) as measure_value from gold.fact_sales
union all 
select 'Total Num of Orders' as measure_name, count(distinct order_number) as measure_value from gold.fact_sales
union all 
select 'Total Num of Products' as measure_name, count(distinct product_id) as measure_value from gold.dim_products
union all 
select 'Total Num of Customers' as measure_name, count(customer_id) as measure_value from gold.dim_customers;

/* =============================================================================================
 * Magnitude Analysis: Compare the measure values by categories to help us understand the 
 * importance of different categories. (value of A GIVEN B) 
   =============================================================================================*/

-- total number of customers by country 
select country, count(customer_id) as num_cust_country from gold.dim_customers group by country order by num_cust_country desc;
-- find the total customers by gender 
select gender, count(customer_id) as gender_cust from gold.dim_customers group by gender order by gender_cust desc;
-- find total products by category 
select category, count(product_key) as products_cat from gold.dim_products group by category order by products_cat desc;
-- find average cost in each category
select category, round(avg(product_key),2) as avg_cost_cat from gold.dim_products group by category order by avg_cost_cat desc;
-- find total revenue by category 
select 
p.category, 
sum(f.sales_amount) as total_revenue 
from gold.fact_sales f 
left join gold.dim_products p on p.product_key = f.product_key
group by p.category
order by total_revenue desc; 
-- find total revenue generated by each customer 
select 
c.customer_key, 
c.first_name, 
c.last_name, 
sum(f.sales_amount) as total_revenue
from gold.fact_sales f 
left join gold.dim_customers c 
on c.customer_key = f.customer_key
group by 
c.customer_key, 
c.first_name, 
c.last_name
order by total_revenue desc;
-- what is the distribution of sold items across countries? 
-- low cardinality values = value with a small amount of possible returns (gender has 2, country has 7)
select 
c.country,
sum(f.quantity) as total_sold_items
from gold.fact_sales f 
left join gold.dim_customers c 
on c.customer_key = f.customer_key 
group by c.country 
order by total_sold_items desc

/* =============================================================================================
 * Ranking Analysis: Order the values of dimensions by measure. Finding top N performers, bottom
 * N performers, ranking dimensions by a measure. 
   =============================================================================================*/
-- Which 5 products generate the highest revenue? 
select
p.product_name, 
sum(f.sales_amount) total_revenue 
from gold.fact_sales f 
left join gold.dim_products p 
on p.product_key = f.product_key 
group by p.product_name 
order by total_revenue desc 
limit 5;

-- with the row_number window function
select
p.product_name, 
sum(f.sales_amount) total_revenue , 
row_number() over(order by sum(f.sales_amount) desc) as rank_products
from gold.fact_sales f 
left join gold.dim_products p 
on p.product_key = f.product_key 
group by p.product_name 
limit 5;

-- What are the 5 worst performing products in terms of sales? 
select
p.product_name, 
sum(f.sales_amount) total_revenue 
from gold.fact_sales f 
left join gold.dim_products p 
on p.product_key = f.product_key 
group by p.product_name 
order by total_revenue asc 
limit 5;

-- Find the top 10 customers who have generated the highest revenue 
select 
c.customer_key, 
c.first_name, 
c.last_name, 
sum(f.sales_amount) as total_revenue 
from gold.fact_sales f 
left join gold.dim_customers c 
on c.customer_key = f.customer_key 
group by c.customer_key, c.first_name, c.last_name 
order by total_revenue
limit 10 

-- and 3 customers with the fewest orders placed 
select 
c.customer_key, 
c.first_name, 
c.last_name, 
count(f.order_number) as num_orders_placed 
from gold.fact_sales f 
left join gold.dim_customers c 
on c.customer_key = f.customer_key 
group by c.customer_key, c.first_name, c.last_name
order by num_orders_placed asc 
limit 3;

